In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\priya sharma\appdata\roaming\jupyter\runtime\video_game_analysis\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("games.csv")
df

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67
1508,1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,413,107
1509,1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,487,206
1510,1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,388,602
1511,1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,239,73

In [4]:
df.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   str
 2   Release Date       1512 non-null   str
 3   Team               1511 non-null   str
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   str
 6   Number of Reviews  1512 non-null   str
 7   Genres             1512 non-null   str
 8   Summary            1511 non-null   str
 9   Reviews            1512 non-null   str
 10  Plays              1512 non-null   str
 11  Playing            1512 non-null   str
 12  Backlogs           1512 non-null   str
 13  Wishlist           1512 non-null   str
dtypes: float64(1), int64(1), str(12)
memory usage: 165.5 KB

In [6]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [7]:
df.isna().sum()

Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

In [8]:
## Rating
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")
df["Rating"]= df["Rating"].fillna(df["Rating"].mean())

## Team
df["Team"] = df["Team"].fillna("Unknown")

## Summary
df["Summary"]= df["Summary"].fillna("No summary")

In [9]:
df.isnull().sum()

Title                0
Release Date         0
Team                 0
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Summary              0
Reviews              0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
dtype: int64

In [10]:
def convert_k(val):
    if isinstance(val, str):
        val = val.replace(",", "").strip()
        if "K" in val:
            return float(val.replace("K", "")) * 1000
        try:
            return float(val)
        except:
            return None
    return val

cols = ["Times Listed", "Number of Reviews", "Plays", "Playing", "Backlogs", "Wishlist"]

for col in cols:
    df[col] = df[col].apply(convert_k)

In [11]:
def convert_k(x):
    if isinstance(x, str) and 'K' in x:
        return float(x.replace('K','')) * 1000
    return x

cols = ["plays","playing","backlogs","wishlist","times_listed","number_of_reviews"]

for col in cols:
    if col in df.columns:
        df[col] = df[col].apply(convert_k)

In [12]:
import re

def clean_text(val):
    if isinstance(val, str):
        # remove quotes and brackets
        val = re.sub(r"[\'\"\[\]]", "", val)
        return val.strip()
    return val

text_cols = ["Title", "Team", "Genres", "Summary", "Reviews"]

for col in text_cols:
    df[col] = df[col].apply(clean_text)

In [13]:
# 1. column names clean
df.columns = df.columns.str.lower().str.replace(" ", "_")

# 2. special characters remove
df = df.replace(r'[^\x00-\x7F]+', '', regex=True)

# 3. quotes + brackets remove
df = df.replace({'"': '', "'": '', r'\[': '', r'\]': ''}, regex=True)

In [14]:
df.columns

Index(['title', 'release_date', 'team', 'rating', 'times_listed',
       'number_of_reviews', 'genres', 'summary', 'reviews', 'plays', 'playing',
       'backlogs', 'wishlist'],
      dtype='str')

In [15]:
df

,title,release_date,team,rating,times_listed,number_of_reviews,genres,summary,reviews,plays,playing,backlogs,wishlist
0,Elden Ring,"Feb 25, 2022","Bandai Namco Entertainment, FromSoftware",4.5,3900.0,3900.0,"Adventure, RPG","Elden Ring is a fantasy, action and open world...",The first playthrough of elden ring is one of ...,17000.0,3800.0,4600.0,4800.0
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2900.0,2900.0,"Adventure, Brawler, Indie, RPG",A rogue-lite hack and slash dungeon crawler in...,convinced this is a roguelike for people who d...,21000.0,3200.0,6300.0,3600.0
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","Nintendo, Nintendo EPD Production Group No. 3",4.4,4300.0,4300.0,"Adventure, RPG",The Legend of Zelda: Breath of the Wild is the...,This game is the game (that is not CS:GO) that...,30000.0,2500.0,5000.0,2600.0
3,Undertale,"Sep 15, 2015","tobyfox, 8-4",4.2,3500.0,3500.0,"Adventure, Indie, RPG, Turn Based Strategy","A small child falls into the Underground, wher...",soundtrack is tied for #1 with nier automata. ...,28000.0,679.0,4900.0,1800.0
4,Hollow Knight,"Feb 24, 2017",Team Cherry,4.4,3000.0,3000.0,"Adventure, Indie, Platform",A 2D metroidvania with an emphasis on close co...,"this games worldbuilding is incredible, with i...",21000.0,2400.0,8300.0,2300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",Telltale Games,3.2,94.0,94.0,"Adventure, Point-and-Click",Back to the Future: The Game is one of Telltal...,Very enjoyable game. The story adds onto the m...,763.0,5.0,223.0,67.0
1508,Team Sonic Racing,"May 21, 2019","Sumo Digital, Sega",2.9,264.0,264.0,"Arcade, Racing",Team Sonic Racing combines the best elements o...,"jogo morto mas bom, not my cup of tea, Compare...",1500.0,49.0,413.0,107.0
1509,Dragons Dogma,"May 22, 2012",Capcom,3.7,210.0,210.0,"Brawler, RPG","Set in a huge open world, Dragons Dogma: Dark ...","Underrated., A grandes rasgos, es como un MMO ...",1100.0,45.0,487.0,206.0
1510,Baldurs Gate 3,"Oct 06, 2020",Larian Studios,4.1,165.0,165.0,"Adventure, RPG, Strategy, Tactical, Turn Based...","An ancient evil has returned to Baldurs Gate, ...","Bu tre bu oyunla girmeye almak hatayd sanrm., ...",269.0,79.0,388.0,602.0
1511,The LEGO Movie Videogame,"Feb 04, 2014","WB Games, TT Fusion",2.8,184.0,184.0,"Adventure, Puzzle",Join Emmet and an unlikely group of resistance...,"Legal, Pretty Average Lego Game But It Was My ...",1700.0,11.0,239.0,73.0

In [16]:
df.drop(columns=["id"], errors='ignore', inplace=True)

In [17]:
df.to_csv("clean_games.csv", index=False, encoding="utf-8-sig")

In [18]:
print(df.columns)

Index(['title', 'release_date', 'team', 'rating', 'times_listed',
       'number_of_reviews', 'genres', 'summary', 'reviews', 'plays', 'playing',
       'backlogs', 'wishlist'],
      dtype='str')